##
# (c) 2021 - Cloud Ops Works LLC - https://cloudops.works/
#            On GitHub: https://github.com/cloudopsworks
#            Distributed Under Apache v2.0 License
#
pipeline:
  - docker
  - helm
#  - zip
staticAnalysis: true
zipGlobs:
  - target/*.jar
  - conf/**
excludeGlobs:
  - Dockerfile
  - .helmignore
  - .dockerignore
  - .git*
  - .git/
  - OWNER*
  - README.md
  - jenkins*
  - charts/
  - cloudopsworks-ci*
  - skafold*
  - original-*.jar
#
## Default node version is 14, uncomment to build with different
# build:
#   java:
#     version: 11
#     dist: adopt
#
## CD pipeline configuration uncomment and configure accordingly to enable
# cd:
#   env: staging
#   preview:
#     enabled: true
#     kubernetes: true
#     domain: example.com