##
# (c) 2021 - Cloud Ops Works LLC - https://cloudops.works/
#            On GitHub: https://github.com/cloudopsworks
#            Distributed Under Apache v2.0 License
#
name: Do Promote command
on:
  repository_dispatch:
    types:
      - promote-command

permissions:
  issues: write
  checks: read
  deployments: write
  contents: read
  packages: read
  statuses: write

jobs:
  check-from-code:
    runs-on: ubuntu-latest
    outputs:
      package_name: ${{ steps.package_name.outputs.result }}
    steps:
      # Proceed with checkout of source with all the references (depth=0)
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          token: ${{ secrets.BOT_TOKEN }}

      # Get the Package name from pom.xml
      - name: Get Package name
        id: package_name
        uses: mikefarah/yq@master
        with:
          cmd: yq e -oy '.project.groupId + "." + .project.artifactId' pom.xml

  promote:
    needs:
      - check-from-code
    uses: {{REPO_OWNER}}/base-app-template/.github/workflows/slash-on-promote.yml@v4
    with:
      package_name: ${{ needs.check-from-code.outputs.package_name }}
      package_type: MAVEN
    secrets:
      token: ${{ secrets.BOT_TOKEN }}
