organization_name: "ORG_NAME"
organization_unit: "ORG_UNIT"
environment_name: "ENV_NAME"
repository_owner: "REPO_OWNER" # Required
#api_files_dir: "relative-path-to-apidefs"
# Optional Additional ENV variables
#maven_options: "-T 1C -Dmaven.wagon.http.retryHandler.count=3"