##
# (c) 2021 - Cloud Ops Works LLC - https://cloudops.works/
#            On GitHub: https://github.com/cloudopsworks
#            Distributed Under Apache v2.0 License
#
name: Static Analysis Process
on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      semver:
        required: false
        type: string
      sonarqubeUrl:
        required: true
        type: string

    secrets:
      BOT_TOKEN:
        required: true
      sonarqubeToken:
        required: true

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      # Proceed with checkout of source with all the references (depth=0)  
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.BOT_TOKEN }}
          ref: ${{ inputs.ref }}
      # Get pipeline conf java version
      - name: Get pipeline node version
        id: java_version
        uses: mikefarah/yq@master
        with:
          cmd: yq e '.build.java.version // "17"' ./.github/cloudopsworks-ci.yaml
      # Get pipeline conf node dist
      - name: Get pipeline java dist
        id: java_dist
        uses: mikefarah/yq@master
        with:
          cmd: yq e '.build.java.dist // "adopt"' ./.github/cloudopsworks-ci.yaml
      # Setup Java JDK for builds
      - name: Set JDK
        uses: actions/setup-java@v4
        with:
          java-version: "${{ steps.java_version.outputs.result }}"
          distribution: "${{ steps.java_dist.outputs.result }}"
      # Cache all maven packages
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      # Run versioning to tag the source
      - name: Run Versioning setup
        run: make version

      # Test the code!
      - name: Static Test Code
        env:
          JAVA_OPTIONS: "-XX:+UnlockExperimentalVMOptions -Dsun.zip.disableMemoryMapping=true -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Xms128m -Xmx2048m"
          SONARQUBE_URL: ${{ inputs.sonarqubeUrl }}
          SONARQUBE_TOKEN: ${{ secrets.sonarqubeToken }}
        run: |
          mvn --batch-mode verify
      - name: Sonar Scan
        uses: sonarsource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.sonarqubeToken }}
          SONAR_HOST_URL: ${{ inputs.sonarqubeUrl }}
        with:
          projectBaseDir: src/main/java
          args: >
            -Dsonar.projectKey=${{ github.repository }}
            -Dsonar.projectName=${{ github.repository }}
            -Dsonar.projectVersion=${{ inputs.semver }}
            -Dsonar.branch.name=${{ github.ref }}
            -Dsonar.language=java