##
# (c) 2021 - Cloud Ops Works LLC - https://cloudops.works/
#            On GitHub: https://github.com/cloudopsworks
#            Distributed Under Apache v2.0 License
#
name: Static Analysis Process
on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      sonarqubeUrl:
        required: true
        type: string

    secrets:
      BOT_TOKEN:
        required: true
      sonarqubeToken:
        required: true

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      # Proceed with checkout of source with all the references (depth=0)  
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.BOT_TOKEN }}
          ref: ${{ inputs.ref }}
      # Get pipeline conf java version
      - name: Get pipeline node version
        id: java_version
        uses: mikefarah/yq@master
        with:
          cmd: yq eval '.build.java.version // "11"' ./cloudopsworks-ci.yaml
      # Get pipeline conf node dist
      - name: Get pipeline java dist
        id: java_dist
        uses: mikefarah/yq@master
        with:
          cmd: yq eval '.build.java.dist // "adopt"' ./cloudopsworks-ci.yaml
      # Setup Java JDK for builds
      - name: Set JDK
        uses: actions/setup-java@v3
        with:
          java-version: "${{ steps.java_version.outputs.result }}"
          distribution: "${{ steps.java_dist.outputs.result }}"
      # Cache all maven packages
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Build the code!
      - name: Static Test Code
        env:
          JAVA_OPTIONS: "-XX:+UnlockExperimentalVMOptions -Dsun.zip.disableMemoryMapping=true -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Xms128m -Xmx2048m"
          SONARQUBE_URL: ${{ inputs.sonarqubeUrl }}
          SONARQUBE_TOKEN: ${{ secrets.sonarqubeToken }}
        run: |
          mvn --batch-mode test
          mvn --batch-mode sonar:sonar -Dsonar.host.url=$SONARQUBE_URL -Dsonar.login=$SONARQUBE_TOKEN
